plugins {
    id 'java-library'
    id 'maven-publish'
    id 'org.jreleaser' version '1.24.0'
}

group = 'com.glencoesoftware'
version = '0.1.0-SNAPSHOT'

compileJava {
    options.release = 11
}

java {
    withJavadocJar()
    withSourcesJar()
}

repositories {
    mavenCentral()
}

dependencies {
    testImplementation "org.scijava:native-lib-loader:2.4.0"
    testRuntimeOnly "org.slf4j:slf4j-api:1.7.6"

    // https://github.com/junit-team/junit5-samples/blob/master/junit5-migration-gradle/build.gradle
    def junitVintageVersion  = '5.7.0'
    def junitJupiterVersion  = '5.7.0'
    def junitPlatformVersion = '1.7.0'
    testImplementation "org.junit.jupiter:junit-jupiter-api:${junitJupiterVersion}"
    testRuntimeOnly "org.junit.jupiter:junit-jupiter-engine:${junitJupiterVersion}"
    testRuntimeOnly "org.junit.platform:junit-platform-launcher:${junitPlatformVersion}"

    // https://stackoverflow.com/questions/45462987/junit5-with-intellij-and-gradle
    testImplementation "org.junit.jupiter:junit-jupiter-params:${junitJupiterVersion}"
}

jar {
    manifest {
        attributes(
            "Created-By": "Gradle ${gradle.gradleVersion}",
            "Build-Jdk": "${System.properties['java.version']} (${System.properties['java.vendor']} ${System.properties['java.vm.version']})",
            "Built-By": System.properties['user.name'],
            "Built-On": new java.text.SimpleDateFormat("yyyy-MM-dd'T'HH:mm:ss.SSSZ").format(new Date()),
            "Main-Class": "org.libjpegturbo.turbojpeg.TJ",
            "Implementation-Version": version,
            "Implementation-Build": "git rev-parse --verify HEAD".execute().getText().trim()
        )
    }
}

test {
    useJUnitPlatform()

    classpath = files("${buildDir}/libs/libjpeg-turbo-java-${version}.jar") + classpath
}

publishing {
    publications {
        maven(MavenPublication) {
            groupId = 'com.glencoesoftware'
            artifactId = 'libjpeg-turbo'

            from components.java

            pom {
                name = 'libjpeg-turbo'
                description = 'JNI-based wrapper around the libjpeg-turbo library.'
                url = 'https://github.com/glencoesoftware/libjpeg-turbo-java'
                inceptionYear = '2022'
                licenses {
                    license {
                        name = 'BSD 3-Clause "New" or "Revised" License'
                        url = 'https://opensource.org/licenses/BSD-3-Clause'
                    }
                }
                developers {
                    developer {
                        id = 'chris-allan'
                        name = 'Chris Allan'
                    }
                    developer {
                        id = 'melissalinkert'
                        name = 'Melissa Linkert'
                    }
                    developer {
                        id = 'sbesson'
                        name = 'Sébastien Besson'
                    }
                }
                scm {
                    connection = 'scm:git:https://github.com/glencoesoftware/libjpeg-turbo-java'
                    developerConnection = 'scm:git:git@github.com:glencoesoftware/libjpeg-turbo-java'
                    url = 'http://github.com/glencoesoftware/libjpeg-turbo-java'
                }
            }
        }
    }

    repositories {
        maven {
            url = layout.buildDirectory.dir('staging-deploy')
        }
    }
}

jreleaser {
    signing {
        pgp {
            active = 'ALWAYS'
            armored = true
        }
    }
    deploy {
        maven {
            mavenCentral {
                'release-deploy' {
                    active = 'ALWAYS'
                    url = 'https://central.sonatype.com/api/v1/publisher'
                    stagingRepository('build/staging-deploy')
                }
            }
            nexus2 {
              'snapshot-deploy' {
                active = 'SNAPSHOT'
                snapshotUrl = 'https://central.sonatype.com/repository/maven-snapshots/'
                applyMavenCentralRules = true
                snapshotSupported = true
                closeRepository = true
                releaseRepository = true
                stagingRepository('build/staging-deploy')
            }
        }
    }
  }
}
