# Dockerfile for lowest common denominator Linux native artifact build
# --------------------------------------------------------------------
# Cribbed from TileDB-Java/ci/Dockerfile2010
FROM quay.io/pypa/manylinux_2_28_x86_64

RUN yum install -y java-11-openjdk-devel
